application: dev-scrumpoker
version: 1
runtime: python27
api_version: 1
threadsafe: yes
default_expiration: "0m"

handlers:
- url: /
  static_files: index.html
  upload: index\.html

- url: /scrumpoker\.xml
  static_files: scrumpoker.xml
  upload: scrumpoker\.xml

- url: /icons/(.*)
  static_files: icons/\1
  upload: icons/(.*)

- url: /js/(.*)
  static_files: js/\1
  upload: js/(.*)

- url: /css/(.*)
  static_files: css/\1
  upload: css/(.*)

- url: /images/(.*)
  static_files: images/\1
  upload: images/(.*)
